name: Android Pull Request & Master CI

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  bundle:
    - name: Restore dayona.jks
      run: echo $KEYSTORE_FILE | base64 -d > /home/dayona/Desktop/keystore/dayona.jks
    - name: Build Release AAB
      run: ./gradlew
        -PKEYSTORE_FILE="../${{ /home/dayona/Desktop/keystore/dayona.jks }}"
        -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
        -PSIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
        -PSIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
        app:bundleRelease
    - name: Build Release AAB
      run: ./gradlew app:bundleRelease
    - name: Upload AAB
      uses: actions/upload-artifact@v1
      with:
        name: aab
        path: app/build/outputs/bundle/release/app-release.aab

#  apk:
#    name: Generate APK
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - name: Build debug APK
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk
